# fly.toml app configuration file generated for everionv011 on 2025-02-10T08:21:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "everionv011"
primary_region = "fra"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  processes = ["app"]

[experimental]
  auto_stop_machines = false
  auto_start_machines = true
  # Optionally, ensure at least one machine is always running:
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
