# fly.toml app configuration file generated for everion-fastapi on 2025-02-10T09:47:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'everion-fastapi'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  size = 'shared-cpu-1x'
